### PR TITLE
Rerender & Update URL

### PR DESCRIPTION
**Pull request by snowman2**
@conda-forge-admin please rerender.

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - hdfeos5
  - libgdal=2.4.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
```

### CODE REVIEW

**Comment by snowman2** [comment]
@ocefpaf it seems the FTP server is down that hosts the files. Are there any other options for updating pins?

**Comment by ocefpaf** [comment]
> @ocefpaf it seems the FTP server is down that hosts the files. Are there any other options for updating pins?

I haven't looked into this for a while. See #22 for a possible new URL.

**Comment by snowman2** [comment]
Aw shucks, looks like the same issue there without resolution.

**Comment by snowman2** [comment]
```
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... none
checking how to run the C++ preprocessor... /lib/cpp
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
```

**Comment by snowman2** [comment]
@conda-forge-admin please rerender.

**Comment by snowman2** [comment]
Patch issues?
```
EHapi.c:11316:2: error: #endif without #if
#endif /* H5_HAVE_FILTER_SZIP */
 ^
EHapi.c:11775:2: error: unterminated conditional directive
#ifdef H5_HAVE_FILTER_SZIP
```

**Comment by snowman2** [comment]
@ocefpaf it passed!

**Comment by ocefpaf** [comment]
> @ocefpaf it passed!

Awesome! Thanks @snowman2!!
Do you want to add yourself as a maintainer?
(Can be done in another PR skipping the CIs.)

**Comment by snowman2** [comment]
> Do you want to add yourself as a maintainer?

Sure, I will do that in a bit.

**Pull request merged**
